table Dim_Date
	lineageTag: 11000001-0001-0001-0001-000000000001
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 11000001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 11000001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: Year

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 11000001-0001-0001-0001-000000000004
		summarizeBy: none
		sourceColumn: Month

	column MonthName
		dataType: string
		lineageTag: 11000001-0001-0001-0001-000000000005
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 11000001-0001-0001-0001-000000000006
		summarizeBy: none
		sourceColumn: Day

	column Quarter
		dataType: string
		lineageTag: 11000001-0001-0001-0001-000000000007
		summarizeBy: none
		sourceColumn: Quarter

	column WeekDay
		dataType: string
		lineageTag: 11000001-0001-0001-0001-000000000008
		summarizeBy: none
		sourceColumn: WeekDay

	column WeekNum
		dataType: int64
		formatString: 0
		lineageTag: 11000001-0001-0001-0001-000000000009
		summarizeBy: none
		sourceColumn: WeekNum

	partition Dim_Date = m
		mode: import
		source =
				let
					StartDate = #date(2020, 1, 1),
					EndDate = #date(2030, 12, 31),
					DayCount = Duration.Days(EndDate - StartDate) + 1,
					DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
					DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
					TypedDate = Table.TransformColumnTypes(DateTable, {{"Date", type date}}),
					AddYear = Table.AddColumn(TypedDate, "Year", each Date.Year([Date]), Int64.Type),
					AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
					AddMonthName = Table.AddColumn(AddMonth, "MonthName", each Date.MonthName([Date]), type text),
					AddDay = Table.AddColumn(AddMonthName, "Day", each Date.Day([Date]), Int64.Type),
					AddQuarter = Table.AddColumn(AddDay, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
					AddWeekDay = Table.AddColumn(AddQuarter, "WeekDay", each Date.DayOfWeekName([Date]), type text),
					AddWeekNum = Table.AddColumn(AddWeekDay, "WeekNum", each Date.WeekOfYear([Date]), Int64.Type)
				in
					AddWeekNum

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

