table Dim_WcagCriterion
	lineageTag: b1000001-0001-0001-0001-000000000001

	column CriterionKey
		dataType: string
		isKey
		lineageTag: b1000001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: CriterionKey

	column CriterionId
		dataType: string
		lineageTag: b1000001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: CriterionId

	column CriterionName
		dataType: string
		lineageTag: b1000001-0001-0001-0001-000000000004
		summarizeBy: none
		sourceColumn: CriterionName

	column Level
		dataType: string
		lineageTag: b1000001-0001-0001-0001-000000000005
		summarizeBy: none
		sourceColumn: Level

	column GuidelineId
		dataType: string
		lineageTag: b1000001-0001-0001-0001-000000000006
		summarizeBy: none
		sourceColumn: GuidelineId

	column GuidelineName
		dataType: string
		lineageTag: b1000001-0001-0001-0001-000000000007
		summarizeBy: none
		sourceColumn: GuidelineName

	partition Dim_WcagCriterion = m
		mode: import
		source =
				let
					Source = Table.FromRows(
						{
							{"1.1.1", "1.1.1", "Non-text Content", "A", "1.1", "Text Alternatives"},
							{"1.2.2", "1.2.2", "Captions (Prerecorded)", "A", "1.2", "Time-based Media"},
							{"1.3.1", "1.3.1", "Info and Relationships", "A", "1.3", "Adaptable"},
							{"1.3.2", "1.3.2", "Meaningful Sequence", "A", "1.3", "Adaptable"},
							{"1.3.5", "1.3.5", "Identify Input Purpose", "AA", "1.3", "Adaptable"},
							{"1.4.3", "1.4.3", "Contrast (Minimum)", "AA", "1.4", "Distinguishable"},
							{"1.4.4", "1.4.4", "Resize Text", "AA", "1.4", "Distinguishable"},
							{"1.4.10", "1.4.10", "Reflow", "AA", "1.4", "Distinguishable"},
							{"1.4.11", "1.4.11", "Non-text Contrast", "AA", "1.4", "Distinguishable"},
							{"1.4.12", "1.4.12", "Text Spacing", "AA", "1.4", "Distinguishable"},
							{"2.1.1", "2.1.1", "Keyboard", "A", "2.1", "Keyboard Accessible"},
							{"2.1.2", "2.1.2", "No Keyboard Trap", "A", "2.1", "Keyboard Accessible"},
							{"2.4.1", "2.4.1", "Bypass Blocks", "A", "2.4", "Navigable"},
							{"2.4.2", "2.4.2", "Page Titled", "A", "2.4", "Navigable"},
							{"2.4.3", "2.4.3", "Focus Order", "A", "2.4", "Navigable"},
							{"2.4.4", "2.4.4", "Link Purpose (In Context)", "A", "2.4", "Navigable"},
							{"2.4.6", "2.4.6", "Headings and Labels", "AA", "2.4", "Navigable"},
							{"2.4.7", "2.4.7", "Focus Visible", "AA", "2.4", "Navigable"},
							{"2.4.11", "2.4.11", "Focus Not Obscured (Minimum)", "AA", "2.4", "Navigable"},
							{"2.5.8", "2.5.8", "Target Size (Minimum)", "AA", "2.5", "Input Modalities"},
							{"3.1.1", "3.1.1", "Language of Page", "A", "3.1", "Readable"},
							{"3.3.2", "3.3.2", "Labels or Instructions", "A", "3.3", "Input Assistance"},
							{"4.1.2", "4.1.2", "Name, Role, Value", "A", "4.1", "Compatible"},
							{"4.1.3", "4.1.3", "Status Messages", "AA", "4.1", "Compatible"}
						},
						{"CriterionKey", "CriterionId", "CriterionName", "Level", "GuidelineId", "GuidelineName"}
					),
					TypedColumns = Table.TransformColumnTypes(Source,
						{{"CriterionKey", type text}, {"CriterionId", type text}, {"CriterionName", type text},
						 {"Level", type text}, {"GuidelineId", type text}, {"GuidelineName", type text}})
				in
					TypedColumns

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

